---
title: "Proposed API for tech.ml.dataset"
author: GenerateMe
date: "`r Sys.Date()`"
output:
    html_document:
        highlight: pygments
        theme: simplex
        toc: true
        toc_depth: 4
        toc_float:
            smooth_scroll: true
            collapsed: true
        includes:
            in_header: better_tables.html
        smart: false
    pdf_document:
        highlight: tango
        latex_engine: xelatex
    md_document:
        variant: markdown_github
---


```{css echo=FALSE}
table { width: auto !important; margin-right: auto; margin-left: 2%; }
h1, h2, h3, h4, h5, h6 { padding-top: 16px; border-bottom: 1px solid; }
```


```{r setup, include=FALSE}
find_nrepl_port_up <- function() {
    wd <- getwd()
    while(wd != dirname(wd)) {
        f <- paste0(wd,"/.nrepl-port")
        if(file.exists(f)) return(paste0("@",f))
        wd <- dirname(wd)
        f <- NULL
    }
}
port_file <- find_nrepl_port_up()
if(is.null(port_file)) stop("nREPL port not found")
library(knitr)
knitr_one_string <- knitr:::one_string
nrepl_cmd  <- "rep"
opts_chunk$set(comment=NA, highlight=TRUE)
knit_engines$set(clojure = function(options) {
    rep_params <- if(isTRUE(options$stdout_only)) {
                      "--print 'out,1,%{out}' --print 'value,1,' -p"
                  } else {
                      "-p"
                  }
    code <- paste(rep_params, port_file, shQuote(knitr_one_string(options$code)))
    out <- if (options$eval) {
               if (options$message) message('running: ', nrepl_cmd, ' ', code)
               tryCatch(
                   system2(nrepl_cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env),
                   error = function(e) {
                       if (!options$error) stop(e)
                       paste('Error in running command', nrepl_cmd)
                   }
               )
           } else ''
    if (!options$error && !is.null(attr(out, 'status'))) stop(knitr_one_string(out))
    engine_output(options, options$code, out)})
```

## Introduction

[tech.ml.dataset](https://github.com/techascent/tech.ml.dataset) is a great and fast library which brings columnar dataset to the Clojure. Chris Nuernberger has been working on this library for last year as a part of bigger `tech.ml` stack.

I've started to test the library and help to fix uncovered bugs. My main goal was to compare functionalities with the other standards from other platforms. I focused on R solutions: [dplyr](https://dplyr.tidyverse.org/), [tidyr](https://tidyr.tidyverse.org/) and [data.table](https://rdatatable.gitlab.io/data.table/).

During conversions of the examples I've come up how to reorganized existing `tech.ml.dataset` functions into simple to use API. The main goals were:

* Focus on dataset manipulation functionality, leaving other parts of `tech.ml` like pipelines, datatypes, readers, ML, etc.
* Single entry point for common operations - one function dispatching on given arguments.
* `group-by` results with special kind of dataset - a dataset containing subsets created after grouping as a column.
* Most operations recognize regular dataset and grouped dataset and process data accordingly.
* One function form to enable thread-first on dataset.

All proposed functions are grouped in tabs below. Select group to see examples and details.

If you want to know more about `tech.ml.dataset` and `tech.ml.datatype` please refer their documentation:

* [Datatype](https://github.com/techascent/tech.datatype/blob/master/docs/cheatsheet.md)
* [Date/time](https://github.com/techascent/tech.datatype/blob/master/docs/datetime.md)
* [Dataset](https://github.com/techascent/tech.ml.dataset/blob/master/docs/walkthrough.md)

INFO: The future of this API is not known yet. Two directions are possible: integration into `tech.ml` or development under `Scicloj` organization. For the time being use this repo if you want to try. Join the discussion on [Zulip](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/api)

Let's require main namespace and define dataset used in most examples:

```{clojure results="hide"}
(require '[techtest.api :as api])
(def DS (api/dataset {:V1 (take 9 (cycle [1 2]))
                      :V2 (range 1 10)
                      :V3 (take 9 (cycle [0.5 1.0 1.5]))
                      :V4 (take 9 (cycle ["A" "B" "C"]))}))
```

```{clojure results="asis"}
DS
```


## Functionality 

### Dataset

Dataset is a special type which can be considered as a map of columns implemented around `tech.ml.datatype` library. Each column can be considered as named sequence of typed data. Supported types include integers, floats, string, boolean, date/time, objects etc.

#### Dataset creation 

Dataset can be created from various of types of Clojure structures and files:

* single values
* sequence of maps
* map of sequences or values
* sequence of columns (taken from other dataset or created manually)
* sequence of pairs
* file types: raw/gzipped csv/tsv, json, xls(x) taken from local file system or URL
* input stream

`api/dataset` accepts:

* data
* options (see documentation of `tech.ml.dataset/->dataset` function for full list):
- `:dataset-name` - name of the dataset
- `:num-rows` - number of rows to read from file
- `:header-row?` - indication if first row in file is a header
- `:key-fn` - function applied to column names (eg. `keyword`, to convert column names to keywords)
- `:separator` - column separator
- `:single-value-column-name` - name of the column when single value is provided

---

Empty dataset.

```{clojure}
(api/dataset)
```

---

Dataset from single value.

```{clojure results="asis"}
(api/dataset 999)
```

---

Set column name for single value. Also set the dataset name.

```{clojure results="asis"}
(api/dataset 999 {:single-value-column-name "my-single-value"})
(api/dataset 999 {:single-value-column-name ""
                  :dataset-name "Single value"})
```

---

Sequence of pairs (first = column name, second = value(s)).

```{clojure results="asis"}
(api/dataset [[:A 33] [:B 5] [:C :a]])
```

---

Not sequential values are repeated row-count number of times.

```{clojure results="asis"}
(api/dataset [[:A [1 2 3 4 5 6]] [:B "X"] [:C :a]])
```

---

Dataset created from map (keys = column name, second = value(s)). Works the same as sequence of pairs.

```{clojure results="asis"}
(api/dataset {:A 33})
(api/dataset {:A [1 2 3]})
(api/dataset {:A [3 4 5] :B "X"})
```

---

You can put any value inside a column

```{clojure results="asis"}
(api/dataset {:A [[3 4 5] [:a :b]] :B "X"})
```

---

Sequence of maps

```{clojure results="asis"}
(api/dataset [{:a 1 :b 3} {:b 2 :a 99}])
(api/dataset [{:a 1 :b [1 2 3]} {:a 2 :b [3 4]}])
```

---

Missing values are marked by `nil`

```{clojure results="asis"}
(api/dataset [{:a nil :b 1} {:a 3 :b 4} {:a 11}])
```

---

Import CSV file

```{clojure results="asis"}
(api/dataset "data/family.csv")
```

---

Import from URL

```{clojure results="hide"}
(defonce ds (api/dataset "https://vega.github.io/vega-lite/examples/data/seattle-weather.csv"))
```

```{clojure results="asis"}
ds
```

#### Saving

Export dataset to a file or output stream can be done by calling `api/write-csv!`. Function accepts:

* dataset
* file name with one of the extensions: `.csv`, `.tsv`, `.csv.gz` and `.tsv.gz` or output stream
* options:
- `:separator` - string or separator char.

```{clojure}
(api/write-csv! ds "output.tsv.gz")
(.exists (clojure.java.io/file "output.csv.gz"))
```

#### Dataset related functions

Summary functions about the dataset like number of rows, columns and basic stats.

---

Number of rows

```{clojure}
(api/row-count ds)
```

---

Number of columns

```{clojure}
(api/column-count ds)
```

---

Shape of the dataset, [row count, column count]

```{clojure}
(api/shape ds)
```

---

General info about dataset. There are three variants:

* default - containing information about columns with basic statistics
* `:basic` - just name, row and column count and information if dataset is a result of `group-by` operation
* `:columns` - columns' metadata

```{clojure results="asis"}
(api/info ds)
(api/info ds :basic)
(api/info ds :columns)
```

---

Getting a dataset name

```{clojure}
(api/dataset-name ds)
```

---

Setting a dataset name (operation is immutable).

```{clojure}
(->> "seattle-weather"
     (api/set-dataset-name ds)
     (api/dataset-name))
```

#### Columns and rows

Get columns and rows as sequences. `column`, `columns` and `rows` treat grouped dataset as regular one. See `Groups` to read more about grouped datasets. 

---

Select column.

```{clojure}
(ds "wind")
(api/column ds "date")
```

---

Columns as sequence

```{clojure}
(take 2 (api/columns ds))
```

---

Columns as map

```{clojure}
(keys (api/columns ds :as-map))
```

---

Rows as sequence of sequences

```{clojure}
(take 2 (api/rows ds))
```

---

Rows as sequence of maps

```{clojure stdout_only=TRUE}
(clojure.pprint/pprint (take 2 (api/rows ds :as-maps)))
```

#### Printing

Dataset is printed using `dataset->str` or `print-dataset` functions. Options are the same as in `tech.ml.dataset/dataset-data->str`. Most important is `:print-line-policy` which can be one of the: `:single`, `:repl` or `:markdown`.

```{clojure stdout_only=TRUE}
(api/print-dataset (api/group-by DS :V1) {:print-line-policy :markdown})
```

```{clojure stdout_only=TRUE}
(api/print-dataset (api/group-by DS :V1) {:print-line-policy :repl})
```


### Group-by

Grouping by is an operation which splits dataset into subdatasets and pack it into new special type of... dataset. I distinguish two types of dataset: regular dataset and grouped dataset. The latter is the result of grouping.

Grouped dataset is annotated in by `:grouped?` meta tag and consist following columns:

* `:name` - group name or structure
* `:group-id` - integer assigned to the group
* `:data` - groups as datasets

Almost all functions recognize type of the dataset (grouped or not) and operate accordingly. 

You can't apply reshaping or join/concat functions on grouped datasets.

#### Grouping

Grouping is done by calling `group-by` function with arguments:

* `ds` - dataset
* `grouping-selector` - what to use for grouping
* options:
    - `:result-type` - what to return:
        * `:as-dataset` (default) - return grouped dataset
        * `:as-indexes` - return rows ids (row number from original dataset)
        * `:as-map` - return map with group names as keys and subdataset as values
        * `:as-seq` - return sequens of subdatasets
    - `:limit-columns` - list of the columns which should be returned during grouping by function.

All subdatasets (groups) have set name as the group name, additionally `group-id` is in meta.

Grouping can be done by:

* single column name
* seq of column names
* map of keys (group names) and row indexes
* value returned by function taking row as map

Note: currently dataset inside dataset is printed recursively so it renders poorly from markdown. So I will use `:as-seq` result type to show just group names and groups.

---

List of columns in groupd dataset

```{clojure}
(api/column-names (api/group-by DS :V1))
```

---

Content of the grouped dataset

```{clojure}
(api/columns (api/group-by DS :V1) :as-map)
```

---

Grouped dataset as map

```{clojure}
(keys (api/group-by DS :V1 {:result-type :as-map}))
```

```{clojure results="asis"}
(vals (api/group-by DS :V1 {:result-type :as-map}))
```

---

Group dataset as map of indexes (row ids)

```{clojure}
(api/group-by DS :V1 {:result-type :as-indexes})
```

---

Grouped datasets are printed as follows by default.

```{clojure results="asis"}
(api/group-by DS :V1)
```

---

To get groups as sequence or a map can be done from grouped dataset using `groups->seq` and `groups->map` functions.

Groups as seq can be obtained by just accessing `:data` column.

I will use temporary dataset here.

```{clojure results="asis"}
(let [ds (-> {"a" [1 1 2 2]
              "b" ["a" "b" "c" "d"]}
             (api/dataset)
             (api/group-by "a"))]
  (seq (ds :data))) ;; seq is not necessary but Markdown treats `:data` as command here
```

```{clojure results="asis"}
(-> {"a" [1 1 2 2]
     "b" ["a" "b" "c" "d"]}
    (api/dataset)
    (api/group-by "a")
    (api/groups->seq))
```

---

Groups as map

```{clojure results="asis"}
(-> {"a" [1 1 2 2]
     "b" ["a" "b" "c" "d"]}
    (api/dataset)
    (api/group-by "a")
    (api/groups->map))
```

---

Grouping by more than one column. You can see that group names are maps. When ungrouping is done these maps are used to restore column names.

```{clojure results="asis"}
(api/group-by DS [:V1 :V3] {:result-type :as-seq})
```

---

Grouping can be done by providing just row indexes. This way you can assign the same row to more than one group.

```{clojure results="asis"}
(api/group-by DS {"group-a" [1 2 1 2]
                  "group-b" [5 5 5 1]} {:result-type :as-seq})
```

---

You can group by a result of gruping function which gets row as map and should return group name. When map is used as a group name, ungrouping restore original column names.

```{clojure results="asis"}
(api/group-by DS (fn [row] (* (:V1 row)
                             (:V3 row))) {:result-type :as-seq})
```

---

You can use any predicate on column to split dataset into two groups.

```{clojure results="asis"}
(api/group-by DS (comp #(< % 1.0) :V3) {:result-type :as-seq})
```

---

`juxt` is also helpful

```{clojure results="asis"}
(api/group-by DS (juxt :V1 :V3) {:result-type :as-seq})
```

--- 

`tech.ml.dataset` provides an option to limit columns which are passed to grouping functions. It's done for performance purposes.

```{clojure results="asis"}
(api/group-by DS identity {:result-type :as-seq
                           :limit-columns [:V1]})
```

#### Ungrouping

Ungrouping simply concats all the groups into the dataset. Following options are possible

* `:order?` - order groups according to the group name ascending order. Default: `false`
* `:add-group-as-column` - should group name become a column? If yes column is created with provided name (or `:$group-name` if argument is `true`). Default: `nil`.
* `:add-group-id-as-column` - should group id become a column? If yes column is created with provided name (or `:$group-id` if argument is `true`). Default: `nil`.
* `:dataset-name` - to name resulting dataset. Default: `nil` (_unnamed)

If group name is a map, it will be splitted into separate columns. Be sure that groups (subdatasets) doesn't contain the same columns already.

If group name is a vector, it will be splitted into separate columns. If you want to name them, set vector of target column names as `:add-group-as-column` argument.

After ungrouping, order of the rows is kept within the groups but groups are ordered according to the internal storage.

---

Grouping and ungrouping.

```{clojure results="asis"}
(-> DS
    (api/group-by :V3)
    (api/ungroup))
```

---

Groups sorted by group name and named.

```{clojure results="asis"}
(-> DS
    (api/group-by :V3)
    (api/ungroup {:order? true
                  :dataset-name "Ordered by V3"}))
```

---

Let's add group name and id as additional columns

```{clojure results="asis"}
(-> DS
    (api/group-by (comp #(< % 4) :V2))
    (api/ungroup {:add-group-as-column true
                  :add-group-id-as-column true}))
```

---

Let's assign different column names

```{clojure results="asis"}
(-> DS
    (api/group-by (comp #(< % 4) :V2))
    (api/ungroup {:add-group-as-column "Is V2 less than 4?"
                  :add-group-id-as-column "group id"}))
```

---

If we group by map, we can automatically create new columns out of group names.

```{clojure results="asis"}
(-> DS
    (api/group-by (fn [row] {"V1 and V3 multiplied" (* (:V1 row)
                                                      (:V3 row))
                            "V4 as lowercase" (clojure.string/lower-case (:V4 row))}))
    (api/ungroup {:add-group-as-column true}))
```

---

We can add group names without separation

```{clojure results="asis"}
(-> DS
    (api/group-by (fn [row] {"V1 and V3 multiplied" (* (:V1 row)
                                                      (:V3 row))
                            "V4 as lowercase" (clojure.string/lower-case (:V4 row))}))
    (api/ungroup {:add-group-as-column "just map"
                  :separate? false}))
```

---

The same applies to group names as sequences

```{clojure results="asis"}
(-> DS
    (api/group-by (juxt :V1 :V3))
    (api/ungroup {:add-group-as-column "abc"}))
```

---

Let's provide column names

```{clojure results="asis"}
(-> DS
    (api/group-by (juxt :V1 :V3))
    (api/ungroup {:add-group-as-column ["v1" "v3"]}))
```

---

Also we can supress separation

```{clojure results="asis"}
(-> DS
    (api/group-by (juxt :V1 :V3))
    (api/ungroup {:separate? false
                  :add-group-as-column true}))
;; => _unnamed [9 5]:


```

#### Other functions

To check if dataset is grouped or not just use `grouped?` function.

```{clojure}
(api/grouped? DS)
```

```{clojure}
(api/grouped? (api/group-by DS :V1))
```

---

If you want to remove grouping annotation (to make all the functions work as with regular dataset) you can use `unmark-group` or `as-regular-dataset` (alias) functions.

It can be important when you want to remove some groups (rows) from grouped dataset using `drop-rows` or something like that.

```{clojure}
(-> DS
    (api/group-by :V1)
    (api/as-regular-dataset)
    (api/grouped?))
```

---

This is considered internal.

If you want to implement your own mapping function on grouped dataset you can call `process-group-data` and pass function operating on datasets. Result should be a dataset to have ungrouping working. 

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/process-group-data #(str "Shape: " (vector (api/row-count %) (api/column-count %))))
    (api/as-regular-dataset))
```

### Columns

Column is a special `tech.ml.dataset` structure based on `tech.ml.datatype` library. For our purposes we cat treat columns as typed and named sequence bound to particular dataset. 

Type of the data is inferred from a sequence during column creation. 

#### Names

To select dataset columns or column names `columns-selector` is used. `columns-selector` can be one of the following:

* `:all` keyword - selects all columns
* column name - for single column
* sequence of column names - for collection of columns
* regex - to apply pattern on column names or datatype
* filter predicate - to filter column names or datatype

Column name can be anything.

`column-names` function returns names according to `columns-selector` and optional `meta-filed`. `meta-field` is one of the following:

* `:name` (default) - to operate on column names
* `:datatype` - to operated on column types
* `:all` - if you want to process all metadata

---

To select all column names you can use `column-names` function.

```{clojure}
(api/column-names DS)
```

or

```{clojure}
(api/column-names DS :all)
```

In case you want to select column which has name `:all` (or is sequence or map), put it into a vector. Below code returns empty sequence since there is no such column in the dataset.

```{clojure}
(api/column-names DS [:all])
```

---

Obviously selecting single name returns it's name if available

```{clojure}
(api/column-names DS :V1)
(api/column-names DS "no such column")
```

---

Select sequence of column names.

```{clojure}
(api/column-names DS [:V1 "V2" :V3 :V4 :V5])
```

---

Select names based on regex, columns ends with `1` or `4`

```{clojure}
(api/column-names DS #".*[14]")
```

---

Select names based on regex operating on type of the column (to check what are the column types, call `(api/info DS :columns)`. Here we want to get integer columns only.

```{clojure}
(api/column-names DS #"^:int.*" :datatype)
```

---

And finally we can use predicate to select names. Let's select double precision columns.

```{clojure}
(api/column-names DS #(= :float64 %) :datatype)
```

---

If you want to select all columns but given, use `complement` function. Works only on a predicate.

```{clojure}
(api/column-names DS (complement #{:V1}))
(api/column-names DS (complement #(= :float64 %)) :datatype)
```

---

You can select column names based on all column metadata at once by using `:all` metadata selector. Below we want to select column names ending with `1` which have `long` datatype.

```{clojure}
(api/column-names DS (fn [meta]
                       (and (= :int64 (:datatype meta))
                            (clojure.string/ends-with? (:name meta) "1"))) :all)
```

#### Select

`select-columns` creates dataset with columns selected by `columns-selector` as described above. Function works on regular and grouped dataset.

---

Select only float64 columns

```{clojure results="asis"}
(api/select-columns DS #(= :float64 %) :datatype)
```

---

Select all but `:V1` columns

```{clojure results="asis"}
(api/select-columns DS (complement #{:V1}))
```

---

If we have grouped data set, column selection is applied to every group separately.

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/select-columns [:V2 :V3])
    (api/groups->map))
```

#### Drop

`drop-columns` creates dataset with removed columns.

---

Drop float64 columns

```{clojure results="asis"}
(api/drop-columns DS #(= :float64 %) :datatype)
```

---

Drop all columns but `:V1` and `:V2`

```{clojure results="asis"}
(api/drop-columns DS (complement #{:V1 :V2}))
```

---

If we have grouped data set, column selection is applied to every group separately. Selected columns are dropped.

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/drop-columns [:V2 :V3])
    (api/groups->map))
```

#### Rename

If you want to rename colums use `rename-columns` and pass map where keys are old names, values new ones.

```{clojure results="asis"}
(api/rename-columns DS {:V1 "v1"
                        :V2 "v2"
                        :V3 [1 2 3]
                        :V4 (Object.)})
```

---

Function works on grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/rename-columns {:V1 "v1"
                         :V2 "v2"
                         :V3 [1 2 3]
                         :V4 (Object.)})
    (api/groups->map))
```


#### Add or update

To add (or update existing) column call `add-or-update-column` function. Function accepts:

* `ds` - a dataset
* `column-name` - if it's existing column name, column will be replaced
* `column` - can be column (from other dataset), sequence, single value or function. Too big columns are always trimmed. Too small are cycled or extended with missing values (according to `size-strategy` argument)
* `size-strategy` (optional) - when new column is shorter than dataset row count, following strategies are applied:
    - `:cycle` (default) - repeat data
    - `:na` - append missing values

Function works on grouped dataset.

---

Add single value as column

```{clojure results="asis"}
(api/add-or-update-column DS :V5 "X")
```

---

Replace one column (column is trimmed)

```{clojure results="asis"}
(api/add-or-update-column DS :V1 (repeatedly rand))
```

---

Copy column

```{clojure results="asis"}
(api/add-or-update-column DS :V5 (DS :V1))
```

---

When function is used, argument is whole dataset and the result should be column, sequence or single value

```{clojure results="asis"}
(api/add-or-update-column DS :row-count api/row-count) 
```

---

Above example run on grouped dataset, applies function on each group separately.

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/add-or-update-column :row-count api/row-count)
    (api/ungroup))
```

---

When column which is added is longer than row count in dataset, column is trimmed. When column is shorter, it's cycled or missing values are appended.

```{clojure results="asis"}
(api/add-or-update-column DS :V5 [:r :b])
```

```{clojure results="asis"}
(api/add-or-update-column DS :V5 [:r :b] :na)
```

---

Tha same applies for grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V3)
    (api/add-or-update-column :V5 [:r :b] :na)
    (api/ungroup))
```

---

Let's use other column to fill groups

```{clojure results="asis"}
(-> DS
    (api/group-by :V3)
    (api/add-or-update-column :V5 (DS :V2))
    (api/ungroup))
```

---

In case you want to add or update several columns you can call `add-or-update-columns` and provide map where keys are column names, vals are columns.

```{clojure results="asis"}
(api/add-or-update-columns DS {:V1 #(map inc (% :V1))
                               :V5 #(map (comp keyword str) (% :V4))
                               :V6 11})
```

#### Map

The other way of creating or updating column is to map columns as regular `map` function. The arity of mapping function should be the same as number of selected columns.

Arguments:

* `ds` - dataset
* `column-name` - target column name
* `map-fn` - mapping function
* `columns-selector` - columns selected
* `meta-field` (optional) - column selector option

---

Let's add numerical columns together

```{clojure results="asis"}
(api/map-columns DS :sum-of-numbers (fn [& rows]
                                      (reduce + rows)) #{:int64 :float64} :datatype)
```

The same works on grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/map-columns :sum-of-numbers (fn [& rows]
                                       (reduce + rows)) #{:int64 :float64} :datatype)
    (api/ungroup))
```

#### Reorder

To reorder columns use columns selectors to choose what columns go first. The unseleted columns are appended to the end.

```{clojure results="asis"}
(api/reorder-columns DS :V4 [:V3 :V2] :V1)
```

---

This function doesn't let you select meta field, so you have to call `column-names` in such case. Below we want to add integer columns at the end.

```{clojure results="asis"}
(api/reorder-columns DS (api/column-names DS (complement #{:int64}) :datatype))
```

#### Type conversion

To convert column into given datatype can be done using `convert-column-type` function. Not all the types can be converted automatically also some types require slow parsing (every conversion from string). In case where conversion is not possible you can pass conversion function.

Arguments:

* `ds` - dataset
* Two options:
    - `coltype-map` in case when you want to convert several columns, keys are column names, vals are new types
    - `colname` and `new-type` - column name and new datatype

`new-type` can be:

* a type like `:int64` or `:string` 
* or pair of datetime and conversion function

After conversion additional infomation is given on problematic values.

The other conversion is casting column into java array (`->array`) of the type column or provided as argument. Grouped dataset returns sequence of arrays.

---

Basic conversion

```{clojure results="asis"}
(-> DS
    (api/convert-column-type :V1 :float64)
    (api/info :columns))
```

---

Using custom converter. Let's treat `:V4` as haxadecimal values. See that this way we can map column to any value.

```{clojure results="asis"}
(-> DS
    (api/convert-column-type :V4 [:int16 #(Integer/parseInt % 16)]))
```

---

You can process several columns at once

```{clojure results="asis"}
(-> DS
    (api/convert-column-type {:V1 :float64
                              :V2 :object
                              :V3 [:boolean #(< % 1.0)]
                              :V4 :object})
    (api/info :columns))
```

---

Function works on the grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/convert-column-type :V1 :float32)
    (api/ungroup)
    (api/info :columns))
```

---

Double array conversion.

```{clojure}
(api/->array DS :V1)
```

---

Function also works on grouped dataset

```{clojure}
(-> DS
    (api/group-by :V3)
    (api/->array :V2))
```

---

You can also cast the type to the other one (if casting is possible):

```{clojure}
(api/->array DS :V4 :string)
(api/->array DS :V1 :float32)
```

### Rows

Rows can be selected or dropped using various selectors:

* row id(s) - row index as number or seqence of numbers (first row has index `0`, second `1` and so on)
* sequence of true/false values
* filter by predicate (argument is row as a map)

When predicate is used you may want to limit columns passed to the function (`limit-columns` option).

Additionally you may want to precalculate some values which will be visible for predicate as additional columns. It's done internally by calling `add-or-update-columns` on a dataset. `:pre` is used as a column definitions.

#### Select

Select fourth row

```{clojure results="asis"}
(api/select-rows DS 4)
```

---

Select 3 rows

```{clojure results="asis"}
(api/select-rows DS [1 4 5])
```

---

Select rows using sequence of true/false values

```{clojure results="asis"}
(api/select-rows DS [true nil nil true])
```

---

Select rows using predicate

```{clojure results="asis"}
(api/select-rows DS (comp #(< % 1) :V3))
```

---

The same works on grouped dataset, let's select first row from every group.

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/select-rows 0)
    (api/ungroup))
```

---

If you want to select `:V2` values which are lower than or equal mean in grouped dataset you have to precalculate it using `:pre`.

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/select-rows (fn [row] (<= (:V2 row) (:mean row)))
                     {:pre {:mean #(tech.v2.datatype.functional/mean (% :V2))}})
    (api/ungroup))
```

#### Drop

`drop-rows` removes rows, and accepts exactly the same parameters as `select-rows`

---

Drop values lower than or equal `:V2` column mean in grouped dataset.

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/drop-rows (fn [row] (<= (:V2 row) (:mean row)))
                   {:pre {:mean #(tech.v2.datatype.functional/mean (% :V2))}})
    (api/ungroup))
```

#### Other

There are several function to select first, last, random rows, or display head, tail of the dataset. All functions work on grouped dataset.

---

First row

```{clojure results="asis"}
(api/first DS)
```

---

Last row

```{clojure results="asis"}
(api/last DS)
```

---

Random row (single)

```{clojure results="asis"}
(api/rand-nth DS)
```

---

Random `n` (default: row count) rows with repetition.

```{clojure results="asis"}
(api/random DS)
```

---

Five random rows with repetition

```{clojure results="asis"}
(api/random DS 5)
```

---

Five random, non-repeating rows

```{clojure results="asis"}
(api/random DS 5 {:repeat? false})
```

---

Shuffle dataset

```{clojure results="asis"}
(api/shuffle DS)
```

---

First `n` rows (default 5)

```{clojure results="asis"}
(api/head DS)
```

---

Last `n` rows (default 5)

```{clojure results="asis"}
(api/tail DS)
```

---

Select 5 random rows from each group

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/random 5)
    (api/ungroup))
```

### Aggregate

Aggregating is a function which produces single row out of dataset. 

Aggregator is a function or sequence or map of functions which accept dataset as an argument and result single value, sequence of values or map.

Where map is given as an input or result, keys are treated as column names.

Grouped dataset is ungrouped after aggreation. This can be turned of by setting `:ungroup` to false. In case you want to pass additional ungrouping parameters add them to the options.

By default resulting column names are prefixed with `summary` prefix (set it with `:default-column-name-prefix` option).

---

Let's calculate mean of some columns

```{clojure results="asis"}
(api/aggregate DS #(reduce + (% :V2)))
```

---

Let's give resulting column a name.

```{clojure results="asis"}
(api/aggregate DS {:sum-of-V2 #(reduce + (% :V2))})
```

--- 

Sequential result is spread into separate columns

```{clojure results="asis"}
(api/aggregate DS #(take 5(% :V2)))
```

---

You can combine all variants and rename default prefix

```{clojure results="asis"}
(api/aggregate DS [#(take 3 (% :V2))
                   (fn [ds] {:sum-v1 (reduce + (ds :V1))
                            :prod-v3 (reduce * (ds :V3))})] {:default-column-name-prefix "V2-value"})
```

---

Processing grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by [:V4])
    (api/aggregate [#(take 3 (% :V2))
                    (fn [ds] {:sum-v1 (reduce + (ds :V1))
                             :prod-v3 (reduce * (ds :V3))})] {:default-column-name-prefix "V2-value"}))
```

Result of aggregating is automatically ungrouped, you can skip this step by stetting `:ungroup` option to `false`.

```{clojure results="asis"}
(-> DS
    (api/group-by [:V3])
    (api/aggregate [#(take 3 (% :V2))
                    (fn [ds] {:sum-v1 (reduce + (ds :V1))
                             :prod-v3 (reduce * (ds :V3))})] {:default-column-name-prefix "V2-value"
                                                              :ungroup? false}))
```

### Order

Ordering can be done by column(s) or any function operating on row. Possible order can be:

* `:asc` for ascending order (default)
* `:desc` for descending order
* custom comparator

`:limit-columns` limits row map provided to ordering functions.

---

Order by single column, ascending

```{clojure results="asis"}
(api/order-by DS :V1)
```

---

Descending order

```{clojure results="asis"}
(api/order-by DS :V1 :desc)
```

---

Order by two columns

```{clojure results="asis"}
(api/order-by DS [:V1 :V2])
```

---

Use different orders for columns

```{clojure results="asis"}
(api/order-by DS [:V1 :V2] [:asc :desc])
```

```{clojure results="asis"}
(api/order-by DS [:V1 :V2] [:desc :desc])
```

```{clojure results="asis"}
(api/order-by DS [:V1 :V3] [:desc :asc])
```

---

Custom function can be used to provied ordering key. Here order by `:V4` descending, then by product of other columns ascending.

```{clojure results="asis"}
(api/order-by DS [:V4 (fn [row] (* (:V1 row)
                                  (:V2 row)
                                  (:V3 row)))] [:desc :asc] {:limit-columns [:V1 :V2 :V3]})
```

---

Custom comparator also can be used in case objects are not comparable by default. Let's define artificial one: if euclidean distance is lower than 2, compare along `z` else along `x` and `y`. We use first three columns for that.

```{clojure}
(defn dist
  [v1 v2]
  (->> v2
       (map - v1)
       (map #(* % %))
       (reduce +)
       (Math/sqrt)))
```

```{clojure results="asis"}
(api/order-by DS [:V1 :V2 :V3] (fn [[x1 y1 z1 :as v1] [x2 y2 z2 :as v2]]
                                 (let [d (dist v1 v2)]
                                   (if (< d 2.0)
                                     (compare z1 z2)
                                     (compare [x1 y1] [x2 y2])))))
```

### Unique

Remove rows which contains the same data. By default `unique-by` removes duplicates from whole dataset. You can also pass list of columns or functions (similar as in `group-by`) to remove duplicates limited by them. Default strategy is to keep the first row. More strategies below.

`unique-by` works on groups

---

Remove duplicates from whole dataset

```{clojure results="asis"}
(api/unique-by DS)
```

---

Remove duplicates from each group selected by column.

```{clojure results="asis"}
(api/unique-by DS :V1)
```

--- 

Pair of columns

```{clojure results="asis"}
(api/unique-by DS [:V1 :V3])
```

---

Also function can be used, split dataset by modulo 3 on columns `:V2`

```{clojure results="asis"}
(api/unique-by DS (fn [m] (mod (:V2 m) 3)))
```

---

The same can be achived with `group-by`

```{clojure results="asis"}
(-> DS
    (api/group-by (fn [m] (mod (:V2 m) 3)))
    (api/first)
    (api/ungroup))
```

---

Grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/unique-by :V1)
    (api/ungroup))
```

#### Strategies

There are 4 strategies defined:

* `:first` - select first row (default)
* `:last` - select last row
* `:random` - select random row
* any function - apply function to a columns which are subject of uniqueness

---

Last

```{clojure results="asis"}
(api/unique-by DS :V1 {:strategy :last})
```

---

Random

```{clojure results="asis"}
(api/unique-by DS :V1 {:strategy :random})
```

---

Pack columns into vector

```{clojure results="asis"}
(api/unique-by DS :V4 {:strategy vec})
```

---

Sum columns

```{clojure results="asis"}
(api/unique-by DS :V4 {:strategy (partial reduce +)})
```

---

Group by function and apply functions

```{clojure results="asis"}
(api/unique-by DS (fn [m] (mod (:V2 m) 3)) {:strategy vec})
```

---

Grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V1)
    (api/unique-by (fn [m] (mod (:V2 m) 3)) {:strategy vec})
    (api/ungroup {:add-group-as-column :from-V1}))
```

### Missing

When dataset contains missing values you can select or drop rows with missing values or replace them using some strategy.

`column-selector` can be used to limit considered columns

Let's define dataset which contains missing values

```{clojure results="hide"}
(def DSm (api/dataset {:V1 (take 9 (cycle [1 2 nil]))
                       :V2 (range 1 10)
                       :V3 (take 9 (cycle [0.5 1.0 nil 1.5]))
                       :V4 (take 9 (cycle ["A" "B" "C"]))}))
```

```{clojure results="asis"}
DSm
```

#### Select

Select rows with missing values

```{clojure results="asis"}
(api/select-missing DSm)
```

---

Select rows with missing values in `:V1`

```{clojure results="asis"}
(api/select-missing DSm :V1)
```

---

The same with grouped dataset

```{clojure results="asis"}
(-> DSm
    (api/group-by :V4)
    (api/select-missing :V3)
    (api/ungroup))
```

#### Drop

Drop rows with missing values

```{clojure results="asis"}
(api/drop-missing DSm)
```

---

Drop rows with missing values in `:V1`

```{clojure results="asis"}
(api/drop-missing DSm :V1)
```

---

The same with grouped dataset

```{clojure results="asis"}
(-> DSm
    (api/group-by :V4)
    (api/drop-missing :V1)
    (api/ungroup))
```

#### Replace

Missing values can be replaced using several strategies. `replace-missing` accepts:

* dataset
* column selector
* value
    - single value
    - sequence of values (cycled)
    - function, applied on column(s) with stripped missings
* strategy (optional)

Strategies are:

* `:value` - replace with given value (default)
* `:up` - copy values up
* `:down` - copy values down

Let's define special dataset here:

```{clojure results="hide"}
(def DSm2 (api/dataset {:a [nil nil nil 1.0 2   nil 4   nil  11 nil nil]
                        :b [2.0   2   2 nil nil 3   nil   3  4  5 5]}))
```

```{clojure results="asis"}
DSm2
```

---

Replace missing with single value in whole dataset

```{clojure results="asis"}
(api/replace-missing DSm2 999)
```

---

Replace missing with single value in `:a` column

```{clojure results="asis"}
(api/replace-missing DSm2 :a 999)
```

---

Replace missing with sequence in `:a` column

```{clojure results="asis"}
(api/replace-missing DSm2 :a [-999 -998 -997])
```

---

Replace missing with a function (mean)

```{clojure results="asis"}
(api/replace-missing DSm2 :a tech.v2.datatype.functional/mean)
```

---

Using `:down` strategy, fills gaps with values from above. You can see that if missings are at the beginning, they are left missing.

```{clojure results="asis"}
(api/replace-missing DSm2 [:a :b] nil :down)
```

---

To fix above issue you can provide value

```{clojure results="asis"}
(api/replace-missing DSm2 [:a :b] 999 :down)
```

---

The same applies for `:up` strategy which is opposite direction.

```{clojure results="asis"}
(api/replace-missing DSm2 [:a :b] 999 :up)
```

---

We can use a function which is applied after applying `:up` or `:down`

```{clojure results="asis"}
(api/replace-missing DSm2 [:a :b] tech.v2.datatype.functional/mean :down)
```

### Join/Separate Columns

Joining or separating columns are operations which can help to tidy messy dataset.

* `join-columns` joins content of the columns (as string concatenation or other structure) and stores it in new column
* `separate-column` splits content of the columns into set of new columns

#### Join

`join-columns` accepts:

* dataset
* column selector (as in `select-columns`)
* options
    - `:separator` (default `"-"`)
    - `:drop-columns?` - whether to drop source columns or not (default `true`)
    - `:result-type`
        * `:map` - packs data into map
        * `:seq` - packs data into sequence
        * `:string` - join strings with separator (default)
        * or custom function which gets row as a vector
    - `:missing-subst` - substitution for missing value

---

Default usage. Create `:joined` column out of other columns.

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4])
```

---

Without dropping source columns.

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:drop-columns? false})
```

---

Let's replace missing value with "NA" string.

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:missing-subst "NA"})
```

---

We can use custom separator.

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:separator "/"
                                             :missing-subst "."})
```

---

Or even sequence of separators.

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:separator ["-" "/"]
                                             :missing-subst "."})
```

---

The other types of results, map:

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:result-type :map})
```

---

Sequence

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:result-type :seq})
```

---

Custom function, calculate hash

```{clojure results="asis"}
(api/join-columns DSm :joined [:V1 :V2 :V4] {:result-type hash})
```

---

Grouped dataset

```{clojure results="asis"}
(-> DSm
    (api/group-by :V4)
    (api/join-columns :joined [:V1 :V2 :V4])
    (api/ungroup))
```

---

##### Tidyr examples

[source](https://tidyr.tidyverse.org/reference/unite.html)

```{clojure}
(def df (api/dataset {:x ["a" "a" nil nil]
                      :y ["b" nil "b" nil]}))
```

```{clojure results="asis"}
df
```

---

```{clojure results="asis"}
(api/join-columns df "z" [:x :y] {:drop-columns? false
                                  :missing-subst "NA"
                                  :separator "_"})
```

---

```{clojure results="asis"}
(api/join-columns df "z" [:x :y] {:drop-columns? false
                                  :separator "_"})
```


#### Separate

Column can be also separated into several other columns using string as separator, regex or custom function. Arguments:

* dataset
* source column
* target columns
* separator as:
    - string - it's converted to regular expression and passed to `clojure.string/split` function
    - regex
    - or custom function (default: identity)
* options
    - `:drop-columns?` - whether drop source column or not (default: `true`)
    - `:missing-subst` - values which should be treated as missing, can be set, sequence, value or function (default: `""`)

Custom function (as separator) should return seqence of values for given value.

---

Separate float into integer and factional values

```{clojure results="asis"}
(api/separate-column DS :V3 [:int-part :frac-part] (fn [^double v]
                                                     [(int (quot v 1.0))
                                                      (mod v 1.0)]))
```

---

Source column can be kept

```{clojure results="asis"}
(api/separate-column DS :V3 [:int-part :frac-part] (fn [^double v]
                                                     [(int (quot v 1.0))
                                                      (mod v 1.0)]) {:drop-column? false})
```

---

We can treat `0` or `0.0` as missing value

```{clojure results="asis"}
(api/separate-column DS :V3 [:int-part :frac-part] (fn [^double v]
                                                     [(int (quot v 1.0))
                                                      (mod v 1.0)]) {:missing-subst [0 0.0]})
```

---

Works on grouped dataset

```{clojure results="asis"}
(-> DS
    (api/group-by :V4)
    (api/separate-column :V3 [:int-part :fract-part] (fn [^double v]
                                                       [(int (quot v 1.0))
                                                        (mod v 1.0)]))
    (api/ungroup))
```

---

Join and separate together.

```{clojure results="asis"}
(-> DSm
    (api/join-columns :joined [:V1 :V2 :V4] {:result-type :map})
    (api/separate-column :joined [:v1 :v2 :v4] (juxt :V1 :V2 :V4)))
```

```{clojure results="asis"}
(-> DSm
    (api/join-columns :joined [:V1 :V2 :V4] {:result-type :seq})
    (api/separate-column :joined [:v1 :v2 :v4] identity))
```

##### Tidyr examples

[separate source](https://tidyr.tidyverse.org/reference/separate.html)
[extract source](https://tidyr.tidyverse.org/reference/extract.html)

```{clojure}
(def df-separate (api/dataset {:x [nil "a.b" "a.d" "b.c"]}))
(def df-separate2 (api/dataset {:x ["a" "a b" nil "a b c"]}))
(def df-separate3 (api/dataset {:x ["a?b" nil "a.b" "b:c"]}))
(def df-extract (api/dataset {:x [nil "a-b" "a-d" "b-c" "d-e"]}))
```

```{clojure results="asis"}
df-separate
```

```{clojure results="asis"}
df-separate2
```

```{clojure results="asis"}
df-separate3
```

```{clojure results="asis"}
df-extract
```

---

```{clojure results="asis"}
(api/separate-column df-separate :x [:A :B] "\\.")
```

---

You can drop columns after separation by setting `nil` as a name. We need second value here.

```{clojure results="asis"}
(api/separate-column df-separate :x [nil :B] "\\.")
```

---

Extra data is dropped

```{clojure results="asis"}
(api/separate-column df-separate2 :x ["a" "b"] " ")
```

---

Split with regular expression

```{clojure results="asis"}
(api/separate-column df-separate3 :x ["a" "b"] "[?\\.:]")
```

---

Or just regular expression to extract values

```{clojure results="asis"}
(api/separate-column df-separate3 :x ["a" "b"] #"(.).(.)")
```

---

Extract first value only

```{clojure results="asis"}
(api/separate-column df-extract :x ["A"] "-")
```

---

Split with regex

```{clojure results="asis"}
(api/separate-column df-extract :x ["A" "B"] #"(\p{Alnum})-(\p{Alnum})")
```

---

Only `a,b,c,d` strings

```{clojure results="asis"}
(api/separate-column df-extract :x ["A" "B"] #"([a-d]+)-([a-d]+)")
```

### Fold/Unroll Rows

To pack or unpack the data into single value you can use `fold-by` and `unroll` functions.

`fold-by` groups dataset and packs columns data from each group separately into desired datastructure (like vector or sequence). `unroll` does the opposite.

#### Fold-by

Group-by and pack columns into vector

```{clojure results="asis"}
(api/fold-by DS [:V3 :V4 :V1])
```

---

You can pack several columns at once.

```{clojure results="asis"}
(api/fold-by DS [:V4])
```

---

You can use custom packing function

```{clojure results="asis"}
(api/fold-by DS [:V4] seq)
```

or

```{clojure results="asis"}
(api/fold-by DS [:V4] set)
```

#### Unroll

`unroll` unfolds sequences stored in data, multiplying other ones when necessary. You can unroll more than one column at once (folded data should have the same size!).

Options:

* `:indexes?` if true (or column name), information about index of unrolled sequence is added.
* `:datatypes` list of datatypes which should be applied to restored columns, a map

---

Unroll one column

```{clojure results="asis"}
(api/unroll (api/fold-by DS [:V4]) [:V1])
```

---

Unroll all folded columns

```{clojure results="asis"}
(api/unroll (api/fold-by DS [:V4]) [:V1 :V2 :V3])
```

---

Unroll one by one leads to cartesian product

```{clojure results="asis"}
(-> DS
    (api/fold-by [:V4 :V1])
    (api/unroll [:V2])
    (api/unroll [:V3]))
```

--- 

You can add indexes

```{clojure results="asis"}
(api/unroll (api/fold-by DS [:V1]) [:V4 :V2 :V3] {:indexes? true})
```

```{clojure results="asis"}
(api/unroll (api/fold-by DS [:V1]) [:V4 :V2 :V3] {:indexes? "vector idx"})
```

---

You can also force datatypes

```{clojure results="asis"}
(-> DS
    (api/fold-by [:V1])
    (api/unroll [:V4 :V2 :V3] {:datatypes {:V4 :string
                                           :V2 :int16
                                           :V3 :float32}})
    (api/info :columns))
```

### Reshape

#### Longer

#### Wider

### Join/Concat

#### Left

#### Right

#### Inner

#### Hash

#### Concat

### Functions

